# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bookmark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bookmark
  pod 'NMapsMap'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Then'
  pod 'RealmSwift', '~>10'
end
