default_platform(:ios)

platform :ios do
  desc "Build app and upload to testflight"
  lane :beta do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180" 
    get_certificates
    get_provisioning_profile
    increment_build_number(
	build_number: latest_testflight_build_number + 1
    )
    build_app(
      configuration: "Debug"
    )
    upload_to_testflight
  end
end